name: PSS2FusionDownscaling
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - openpyxl
  - scikit-learn
  - joblib
  - rasterio
  - gdal
  - pip
  - pip:
    - tensorflow>=2.11
    - keras>=2.11
    - UAVBiophysicalModelling @ git+https://github.com/UEA-Irta/UAVBiophysicalModelling.git
    - pyDMS @ git+https://github.com/radosuav/pyDMS.git
